# Usa una imagen base de Node.js
FROM node:16

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y el package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias y nodemon de manera global
RUN npm install && npm install -g nodemon

# Copia el resto del código de la aplicación al contenedor
COPY . .

# Expone el puerto 8001 en el que correrá tu aplicación
EXPOSE 8002

# Comando para correr la aplicación
CMD ["npm", "start"]
